### ISSUE TITLE
Why do you have so many dependencies ?

### ISSUE THREAD

**Issue by baseplate-admin** [tokitouq/Finstagram#46]
https://github.com/tokitouq/Finstagram/blob/a69747bfdea27d6c39acaa0a360763aeb83d7371/pyproject.toml#L11-L50

**Comment by tokitouq** [comment]
These are flet dependencies maybe?

**Comment by baseplate-admin** [comment]
You never define these

**Comment by tokitouq** [comment]
> You never define these

Define dependencies?
sounds like there is still something I dont know about poetry?
